name: dispatch_pi_dart
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.7
  clock: ^1.1.1
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mysql1: ^0.20.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
